// apps/playground-vue/src/App.vue
<template>
  <div>
    <header :style="{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px' }">
      <h1>{{ t('app.title') }}</h1>
      <button @click="toggleEditor" :style="{ marginLeft: '8px', backgroundColor: isActive ? '#ef4444' : '#22c55e', color: 'white', border: 'none', borderRadius: '4px', padding: '8px 16px', cursor: 'pointer' }">
        {{ isActive ? '✕ Close Editor' : '✎ Open Editor' }}
      </button>
    </header>

    <p :style="{ color: '#64748b', marginBottom: '16px' }">
      <span v-localive-tag="'app.subtitle'">{{ t('app.subtitle') }}</span>
    </p>

    <nav>
      <button :class="{ active: currentLocale === 'en' }" @click="switchLocale('en')">English</button>
      <button :class="{ active: currentLocale === 'fr' }" @click="switchLocale('fr')">Français</button>
    </nav>

    <div class="card" :style="{ marginTop: '16px' }">
      <h2><span v-localive-tag="'card.welcome'">{{ t('card.welcome') }}</span></h2>
      <p><span v-localive-tag="'card.description'">{{ t('card.description') }}</span></p>
    </div>

    <footer :style="{ marginTop: '24px', color: '#94a3b8', fontSize: '14px' }">
      <span v-localive-tag="'footer.rights'">{{ t('footer.rights') }}</span>
    </footer>

    <LiveEditorOverlay />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useLocaliveEditor, localiveSymbol, vLocaliveTag, LiveEditorOverlay } from '@localive/vue';
import { inject } from 'vue';

const { t, locale } = useI18n();
const instance = inject(localiveSymbol)!;
const { isActive, activate, deactivate } = useLocaliveEditor(instance);
const currentLocale = ref(locale.value);

function switchLocale(lng: string) {
  locale.value = lng;
  currentLocale.value = lng;
}

function toggleEditor() {
  if (isActive.value) {
    deactivate();
  } else {
    activate();
  }
}
</script>

// apps/playground-react/src/App.tsx
import { useState, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { LocaliveProvider } from '@localive/react';
import { withI18next } from '@localive/adapter-i18next';
import { useLocaliveEditor } from '@localive/react';
import { useLocaliveTag } from '@localive/react';
import { LiveEditorOverlay } from '@localive/react';
import i18n from './i18n';

function LanguageSwitcher() {
  const { i18n: i18nInstance } = useTranslation();
  const [current, setCurrent] = useState(i18nInstance.language);

  const switchTo = (lng: string) => {
    i18nInstance.changeLanguage(lng);
    setCurrent(lng);
  };

  return (
    <nav>
      <button className={current === 'en' ? 'active' : ''} onClick={() => switchTo('en')}>English</button>
      <button className={current === 'fr' ? 'active' : ''} onClick={() => switchTo('fr')}>Français</button>
    </nav>
  );
}

function EditorToggle() {
  const { isActive, toggle } = useLocaliveEditor();
  return (
    <button onClick={toggle} style={{ marginLeft: '8px', backgroundColor: isActive ? '#ef4444' : '#22c55e', color: 'white', border: 'none', borderRadius: '4px', padding: '8px 16px', cursor: 'pointer' }}>
      {isActive ? '✕ Close Editor' : '✎ Open Editor'}
    </button>
  );
}

function TaggedText({ tKey, children }: { tKey: string; children: string }) {
  const { getTagProps } = useLocaliveTag();
  return <span {...getTagProps(tKey)}>{children}</span>;
}

function AppContent() {
  const { t } = useTranslation();

  return (
    <div>
      <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px' }}>
        <h1>{t('app.title')}</h1>
        <EditorToggle />
      </header>

      <p style={{ color: '#64748b', marginBottom: '16px' }}>
        <TaggedText tKey="app.subtitle">{t('app.subtitle')}</TaggedText>
      </p>

      <LanguageSwitcher />

      <div className="card" style={{ marginTop: '16px' }}>
        <h2>
          <TaggedText tKey="card.welcome">{t('card.welcome')}</TaggedText>
        </h2>
        <p>
          <TaggedText tKey="card.description">{t('card.description')}</TaggedText>
        </p>
      </div>

      <footer style={{ marginTop: '24px', color: '#94a3b8', fontSize: '14px' }}>
        <TaggedText tKey="footer.rights">{t('footer.rights')}</TaggedText>
      </footer>
    </div>
  );
}

export default function App() {
  const adapter = useMemo(() => withI18next(i18n), [i18n]);
  const locales = useMemo(() => ['en', 'fr'], []);

  return (
    <LocaliveProvider
      adapter={adapter}
      locales={locales}
      defaultLocale="en"
    >
      <AppContent />
      <LiveEditorOverlay />
    </LocaliveProvider>
  );
}
